version: '3.8'

services:
  app_fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app_fastapi
    environment:
      - PYTHONUNBUFFERED=1
    command: poetry run uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
  
  app_mercado_livre:
    image: app_mercado_livre:latest
    build:
      context: .
      dockerfile: docker/ws_mercado_livre/Dockerfile
    container_name: app_mercado_livre
    environment:
      - PYTHONUNBUFFERED=1
    command: poetry run python app.py

  # test:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: fastapi_tests
  #   environment:
  #     - PYTHONUNBUFFERED=1
  #   command: poetry run pytest
