FROM ubuntu:24.04

USER root

RUN apt-get update && apt-get install -y \ 
    #python3 \
    python3-pip \
    wget \
    unzip \
    curl \
    xvfb \
    && rm -rf /var/lib/apt/lists/*

RUN Xvfb :99 & \
    export DISPLAY=:99

RUN wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb && \
    dpkg -i google-chrome-stable_current_amd64.deb || apt-get install -f -y && \
    rm google-chrome-stable_current_amd64.deb

RUN ln -s /usr/bin/python3 /usr/bin/python

WORKDIR /app
RUN python3 --version

COPY requirements_test.txt /app/requirements.txt
RUN pip install -r requirements.txt --break-system-packages

COPY ./src/examples/selenium_example.py /app/selenium_example.py
COPY ./drivers /app/drivers
RUN chmod 775 -R drivers 

RUN apt-get remove --purge -y \
    && apt-get autoremove -y \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

#CMD ["python3", "selenium_example.py"]
#python3 selenium_example.py
CMD ["tail", "-f", "/dev/null"]
