# FROM python:3.12-slim

# RUN apt-get update && apt-get install -y --no-install-recommends \
#     wget \
#     unzip \
#     curl \
#     xvfb && \
#     rm -rf /var/lib/apt/lists/*

# FROM ubuntu:22.04

# USER root

# RUN apt-get update && \
#     apt-get install -y python3 python3-pip wget unzip curl xvfb && \
#     rm -rf /var/lib/apt/lists/*

FROM selenium/standalone-chrome:latest

USER root

RUN apt-get update && apt-get install -y python3 python3-pip python3-venv && \
    rm -rf /var/lib/apt/lists/*

# RUN Xvfb :99 & \
#     export DISPLAY=:99

# RUN wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb && \
#     dpkg -i google-chrome-stable_current_amd64.deb || apt-get install -f -y && \
#     rm google-chrome-stable_current_amd64.deb

RUN python3 -m venv /opt/.venv
ENV PATH=/opt/.venv/bin:$PATH

WORKDIR /app
RUN pip install --upgrade pip

# RUN curl -sSL https://install.python-poetry.org | python3 -
# ENV PATH="/root/.local/bin:$PATH"
# COPY ./pyproject.toml ./poetry.lock ./
# RUN poetry install --no-root --break-system-packages

COPY requirements.txt .
RUN pip install -r requirements.txt

COPY ./src/ws_amazon .
COPY ./drivers ./drivers

RUN chmod 775 -R drivers 

RUN apt-get remove --purge -y \
    && apt-get autoremove -y \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

CMD ["tail", "-f", "/dev/null"]
#CMD ["poetry", "run", "python", "app.py"]
