executor: "KubernetesExecutor"

webserverSecretKeySecretName: my-webserver-secret-key

env:
  - name: AIRFLOW__CORE__LOAD_EXAMPLES
    value: "False"

extraSecrets:
  my-webserver-secret-key:
    data: |
      webserver-secret-key: T0s1dXpyNXZDOWtYOExQWld6cE1qd2VLS2ZKdnNxMlc=

# images:
#   airflow:
#     repository: jnyjhow/app_airflow
#     tag: "latest"
