apiVersion: batch/v1
kind: CronJob
metadata:
  name: app-mercado-livre-cron
spec:
  #schedule: "0 19 * * *"
  schedule: "*/10 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: app-mercado-livre
            image: jnyjhow/app_mercado_livre:latest
            imagePullPolicy: Always
            command: ["poetry", "run", "python", "app.py"]
          restartPolicy: OnFailure
