apiVersion: batch/v1
kind: CronJob
metadata:
  name: app-mercado-livre-cron
spec:
  schedule: "0 19 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: app-mercado-livre
            image: jnyjhow/app_mercado_livre:latest
            imagePullPolicy: Always
            # env:
            # - name: ENV_VAR_NAME
            #   value: "example-value"
          restartPolicy: OnFailure
