name: CI Dev - Local

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  test-local:
    runs-on: ubuntu-latest
    environment: dev

    strategy:
      matrix:
        python-version: [3.11, 3.12, 3.13]

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        echo "export PATH=$HOME/.local/bin:\$PATH" >> $GITHUB_ENV
        poetry --version
    
    - name: Install dependencies with Poetry
      run: |
        poetry install
    
    - name: Start FastAPI server
      run: |
        nohup poetry run uvicorn src.main:app --host 0.0.0.0 --port 8000 &
        sleep 5

    - name: Test FastAPI endpoint
      run: |
        curl -f http://127.0.0.1:8000/ | grep "Hello, World!"

    - name: Test FastAPI with pytest
      run: |
        poetry run pytest

    - name: Stop FastAPI server
      run: |
        pkill -f "uvicorn"

    - name: Test app_mercado_livre
      run: |
        poetry run python ./src/ws_mercado_livre/app.py
