name: CI Homolog - Build and Push Docker Image Airflow

on:
  pull_request:
    branches:
      - main

jobs:
  test_docker-airflow:
    runs-on: ubuntu-latest
    environment: homolog
    env:
      DOCKER_IMAGE_NAME: app_airflow
      DOCKER_REGISTRY: ${{ vars.DOCKER_REGISTRY }}

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Generate UUID Version
        id: uuid_version
        uses: actions/github-script@v6
        with:
          script: return crypto.randomUUID()

      - name: Build and Push Docker Image
        run: |
          IMAGE_NAME="${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE_NAME }}"
          UUID_VERSION=${{ steps.uuid_version.outputs.uuid }}
          docker build -f docker/airflow/Dockerfile -t $IMAGE_NAME:latest -t $IMAGE_NAME:$UUID_VERSION .
          docker push $IMAGE_NAME --all-tags

      - name: Post-build cleanup
        run: docker image prune -af
