name: CI Test Kubernetes Locally

on:
  pull_request:
    branches:
      - main

jobs:
  test-k8s-locally:
    runs-on: ubuntu-latest
    environment: homolog

    steps:
    - name: Wait for Django CI Homolog - Docker
      uses: lewagon/wait-on-check-action@v1.3.4
      with:
        ref: ${{ github.ref }}
        check-name: 'Run Django CI Homolog - Docker'
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        wait-interval: 10

    - name: Checkout the code
      uses: actions/checkout@v3

    - name: Download success artifact
      uses: actions/download-artifact@v3
      with:
        name: docker-test-success

    - name: Check if Docker test was successful
      run: |
        if grep -q "success" success.txt; then
          echo "Docker tests passed. Proceeding with Kubernetes deployment...";
        else
          echo "Docker tests failed or not found. Exiting.";
          exit 1;
        fi

    - name: Set up Docker
      uses: docker/setup-buildx-action@v3
      with:
        version: latest

    - name: Install KinD
      run: |
        curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.20.0/kind-linux-amd64
        chmod +x ./kind
        sudo mv ./kind /usr/local/bin/kind

    - name: Create Kubernetes cluster
      run: kind create cluster --name test-cluster

    - name: Install kubectl
      run: |
        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        chmod +x ./kubectl
        sudo mv ./kubectl /usr/local/bin/kubectl

    - name: Apply CronJob YAML
      run: |
        kubectl apply -f k8s/base/jobs/cronjob-app-mercado-livre.yaml

    - name: Run the CronJob manually
      run: |
        kubectl create job --from=cronjob/app-mercado-livre-cron app-mercado-livre-manual

    - name: Check Job Status
      run: |
        kubectl get jobs
        kubectl logs job/app-mercado-livre-manual
    
    - name: Delete Kubernetes cluster
      if: always()
      run: kind delete cluster --name test-cluster
